name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Oder dein Hauptbranch-Name

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get
        working-directory: flutter_app # Falls dein Flutter-Projekt in diesem Unterordner liegt

      - name: Build Web
        run: flutter build web --release --base-href "/AmatuerScoutAt/" --no-tree-shake-icons
        working-directory: flutter_app

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./flutter_app/build/web